kind: ConfigMap
apiVersion: v1
metadata:
  name: dockerfile
data:
  Dockerfile: |-
    FROM openjdk:17-jdk-alpine

    WORKDIR /app

    COPY target/*.jar /app/tngb-poc-case1.jar

    EXPOSE 5000

    ENTRYPOINT ["java", "-jar", "tngb-poc-case1.jar"]
